name: Build and Release

on:
  push:
    tags:
      - 'v*'  # 버전 태그가 푸시될 때마다 워크플로가 실행됩니다.

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r aligo/requirements.txt

      - name: Install PyInstaller
        run: pip install pyinstaller

      - name: Build executable
        run: pyinstaller --onefile --name TreeNut --icon ClassLinker_PyQT/treenut.ico ClassLinker_PyQT/TreeNut.py

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
        env:
          GITHUB_TOKEN: ${{ secrets.TREENUT_JMEDU_760329 }}

      - name: Upload Release Asset
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./dist/TreeNut
          asset_name: TreeNut
          asset_content_type: application/octet-stream
